---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sidecar-injector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    istio: {{ template "sidecar-injector.name" . }}
spec:
  ports:
  - port: 443
  selector:
    istio: {{ template "sidecar-injector.name" . }}
---
